pub mod admin_handlers;
pub mod asset_handlers;
pub mod auth_handlers;
pub mod blacklist_handlers;
pub mod company_handlers;
pub mod discovery_handlers;
pub mod drift_handlers;
pub mod evidence_handlers;
pub mod finding_handlers;
pub mod finding_type_config_handlers;
pub mod health_handlers;
pub mod metrics_handlers;
pub mod risk_handlers;
pub mod scan_handlers;
pub mod search_handlers;
pub mod security_handlers;
pub mod settings_handlers;
pub mod static_handlers;
pub mod tag_handlers;

pub use health_handlers::{health_check, health_check_simple, liveness_check, readiness_check};
pub use static_handlers::{serve_evidence_file, static_files_health_check};
